// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/jflex/dexpr.jflex

/*
 *  @(#) dexpr.flex
 *  Copyright 2003 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *   This source, for JFlex (https://jflex.de/)
 */
package com.github.comelf.dexpr;

import com.github.comelf.dexpr.err.DexprTokenException;
import com.github.comelf.dexpr.DexprType;


@SuppressWarnings("fallthrough")
public class DexprFlex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int VAR = 4;
  public static final int STRING_STATE = 6;
  public static final int STRING_VAR = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\1\0\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\12\24\1\25"+
    "\1\0\1\26\1\27\1\30\1\31\1\0\32\32\1\33"+
    "\1\34\1\35\1\0\1\36\1\0\1\37\2\32\1\40"+
    "\1\41\1\42\2\32\1\43\1\32\1\44\1\45\1\32"+
    "\1\46\1\47\2\32\1\50\1\51\1\52\1\53\5\32"+
    "\1\54\1\55\1\56\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\1\1\3\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\1\1\21\1\22\1\4\1\23"+
    "\1\24\6\4\1\25\1\1\1\26\1\27\2\30\1\4"+
    "\2\31\1\32\1\33\1\34\1\35\1\36\1\34\1\37"+
    "\1\34\1\40\1\4\1\41\1\42\1\0\1\43\1\0"+
    "\1\44\1\0\1\45\1\0\1\46\1\47\1\50\5\4"+
    "\1\51\1\4\1\51\1\52\1\53\1\4\1\54\1\34"+
    "\1\55\1\56\1\57\1\60\1\0\1\61\1\44\5\4"+
    "\1\62\1\0\1\63\1\64\3\0\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\353\0\u01d6\0\u0205\0\353\0\353\0\353"+
    "\0\353\0\353\0\353\0\u0234\0\u0263\0\353\0\u0292\0\u02c1"+
    "\0\u02f0\0\353\0\u031f\0\353\0\353\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\353\0\u0468\0\u0497\0\353\0\u04c6"+
    "\0\u04f5\0\u0524\0\u0553\0\u0582\0\353\0\353\0\u05b1\0\353"+
    "\0\353\0\u05e0\0\353\0\u060f\0\353\0\u063e\0\353\0\353"+
    "\0\u0178\0\353\0\u066d\0\353\0\u0205\0\353\0\u069c\0\353"+
    "\0\353\0\353\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u031f"+
    "\0\u07b6\0\353\0\353\0\353\0\u07e5\0\353\0\353\0\353"+
    "\0\353\0\353\0\353\0\u0814\0\u069c\0\u031f\0\u0843\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u031f\0\u092e\0\u031f\0\u031f\0\u095d"+
    "\0\u098c\0\u09bb\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\2\7\1\6\2\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\6\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\6\1\35\1\33\1\36\2\33\1\37"+
    "\2\33\1\40\1\41\1\42\2\33\1\43\1\33\1\44"+
    "\1\45\1\6\2\46\1\47\13\46\1\50\4\46\1\51"+
    "\33\46\1\52\1\53\1\54\1\52\1\54\1\53\46\52"+
    "\1\55\1\52\1\56\2\57\1\60\4\57\1\61\1\62"+
    "\2\57\1\63\20\57\1\64\22\57\1\65\2\7\1\6"+
    "\2\7\24\65\1\66\4\65\15\66\2\65\1\67\60\0"+
    "\2\7\1\0\2\7\100\0\1\70\27\0\7\71\1\72"+
    "\1\0\23\71\1\0\22\71\10\0\1\33\11\0\1\73"+
    "\1\0\1\33\5\0\1\33\3\0\16\33\1\44\14\0"+
    "\1\74\44\0\10\75\1\0\2\75\1\72\20\75\1\0"+
    "\22\75\16\0\1\76\62\0\1\77\1\0\1\25\61\0"+
    "\1\100\56\0\1\101\56\0\1\102\37\0\1\33\11\0"+
    "\1\73\1\0\1\33\5\0\1\33\3\0\16\33\13\0"+
    "\1\33\11\0\1\73\1\0\1\33\5\0\1\33\3\0"+
    "\10\33\1\103\5\33\13\0\1\33\11\0\1\73\1\0"+
    "\1\33\5\0\1\33\3\0\1\33\1\104\14\33\13\0"+
    "\1\33\11\0\1\73\1\0\1\33\5\0\1\33\3\0"+
    "\5\33\1\105\10\33\13\0\1\33\11\0\1\73\1\0"+
    "\1\33\5\0\1\33\3\0\11\33\1\106\3\33\1\107"+
    "\13\0\1\33\11\0\1\73\1\0\1\33\5\0\1\33"+
    "\3\0\12\33\1\110\3\33\13\0\1\33\11\0\1\73"+
    "\1\0\1\33\5\0\1\33\3\0\12\33\1\111\3\33"+
    "\60\0\1\112\1\0\2\46\1\0\13\46\1\0\4\46"+
    "\1\0\33\46\23\0\1\113\51\0\1\114\40\0\2\52"+
    "\1\0\1\52\1\0\47\52\1\0\1\52\1\0\1\52"+
    "\1\53\1\54\1\52\1\54\1\53\46\52\1\0\1\52"+
    "\2\0\2\54\1\0\2\54\51\0\2\57\1\0\4\57"+
    "\2\0\2\57\1\0\20\57\1\0\22\57\32\0\1\115"+
    "\4\0\15\115\1\116\11\0\1\117\3\0\1\117\20\0"+
    "\1\120\11\0\1\121\1\0\1\122\1\0\1\123\14\0"+
    "\1\66\13\0\1\66\5\0\1\66\1\0\1\124\1\0"+
    "\16\66\13\0\1\115\21\0\1\115\3\0\16\115\27\0"+
    "\1\125\42\0\1\33\11\0\1\73\1\0\1\33\5\0"+
    "\1\33\3\0\2\33\1\126\13\33\13\0\1\33\11\0"+
    "\1\73\1\0\1\33\5\0\1\33\3\0\7\33\1\127"+
    "\6\33\13\0\1\33\11\0\1\73\1\0\1\33\5\0"+
    "\1\33\3\0\6\33\1\130\7\33\13\0\1\33\11\0"+
    "\1\73\1\0\1\33\5\0\1\33\3\0\14\33\1\131"+
    "\1\33\13\0\1\33\11\0\1\73\1\0\1\33\5\0"+
    "\1\33\3\0\7\33\1\132\6\33\13\0\1\33\11\0"+
    "\1\73\1\0\1\33\5\0\1\33\3\0\15\33\1\133"+
    "\13\0\1\115\13\0\1\115\5\0\1\115\3\0\16\115"+
    "\25\0\1\66\44\0\1\33\11\0\1\73\1\0\1\33"+
    "\5\0\1\33\3\0\13\33\1\133\2\33\13\0\1\33"+
    "\11\0\1\73\1\0\1\33\5\0\1\33\3\0\3\33"+
    "\1\134\12\33\10\0\1\135\2\0\1\33\11\0\1\73"+
    "\1\0\1\33\5\0\1\33\3\0\16\33\13\0\1\33"+
    "\11\0\1\73\1\0\1\33\5\0\1\33\3\0\7\33"+
    "\1\136\6\33\13\0\1\33\11\0\1\73\1\0\1\33"+
    "\5\0\1\33\3\0\3\33\1\137\12\33\50\0\1\140"+
    "\54\0\1\141\57\0\1\142\53\0\1\143\15\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2538];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\4\1\1\11\2\1\6\11\2\1\1\11"+
    "\3\1\1\11\1\1\2\11\6\1\1\11\2\1\1\11"+
    "\5\1\2\11\1\1\2\11\1\1\1\11\1\1\1\11"+
    "\1\1\2\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\3\11\7\1\3\11\1\1\6\11\1\0\10\1"+
    "\1\0\2\1\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[99];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private int comment_count = 0;
    private int lastTokenStart = -1;
    private char stringDelimiter = '"'; // 문자열 구분자 저장 (" 또는 ')
    private StringBuilder stringBuffer = new StringBuilder();

    public void revertPosition() throws DexprTokenException {
        if(lastTokenStart == -1){
            throw new DexprTokenException("Cannot revert - no previous token");
        }

        this.yychar = lastTokenStart;
        this.zzMarkedPos = lastTokenStart;
        this.zzStartRead = lastTokenStart;
        this.zzCurrentPos = lastTokenStart;
    }

    private DexprToken createToken(com.github.comelf.dexpr.DexprType type) {
        lastTokenStart = zzStartRead;
        return new DexprToken(type, yytext());
    }

    private DexprToken createWrappedToken(com.github.comelf.dexpr.DexprType type) throws DexprTokenException {
        lastTokenStart = zzStartRead;
        switch (type){
            case STRING:
                return new DexprToken(com.github.comelf.dexpr.DexprType.STRING, yytext().substring(1, yytext().length() - 1));
            case STRING_PART:
                return new DexprToken(com.github.comelf.dexpr.DexprType.STRING_PART, yytext());
            case BOOLEAN:
                return new DexprToken(com.github.comelf.dexpr.DexprType.BOOLEAN, Boolean.valueOf(yytext()));
            case DOUBLE:
                return new DexprToken(com.github.comelf.dexpr.DexprType.DOUBLE, Double.valueOf(yytext()));
            case DECIMAL:
                return new DexprToken(com.github.comelf.dexpr.DexprType.DECIMAL, Long.valueOf(yytext()));
            case INTEGER:
                return new DexprToken(com.github.comelf.dexpr.DexprType.INTEGER, Integer.valueOf(yytext()));
            default:
                throw new DexprTokenException("Invalid Token type");
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public DexprFlex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public DexprToken yylex() throws java.io.IOException
    , DexprTokenException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case VAR: {
              throw new DexprTokenException("Unclosed variable");
            }  // fall though
            case 100: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new DexprTokenException("Illegal character : "+yytext());
            }
          // fall through
          case 54: break;
          case 2:
            { /* 공백 무시 */
            }
          // fall through
          case 55: break;
          case 3:
            { stringDelimiter = '"';
        stringBuffer.setLength(0);
        yybegin(STRING_STATE);
        return createToken(com.github.comelf.dexpr.DexprType.STRING_START);
            }
          // fall through
          case 56: break;
          case 4:
            { return createToken(com.github.comelf.dexpr.DexprType.VARIABLE);
            }
          // fall through
          case 57: break;
          case 5:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_MOD);
            }
          // fall through
          case 58: break;
          case 6:
            { stringDelimiter = '\'';
        stringBuffer.setLength(0);
        yybegin(STRING_STATE);
        return createToken(com.github.comelf.dexpr.DexprType.STRING_START);
            }
          // fall through
          case 59: break;
          case 7:
            { return createToken(com.github.comelf.dexpr.DexprType.PARENTHESIS_OPEN);
            }
          // fall through
          case 60: break;
          case 8:
            { return createToken(com.github.comelf.dexpr.DexprType.PARENTHESIS_CLOSE);
            }
          // fall through
          case 61: break;
          case 9:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_MUL);
            }
          // fall through
          case 62: break;
          case 10:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_ADD);
            }
          // fall through
          case 63: break;
          case 11:
            { return createToken(com.github.comelf.dexpr.DexprType.COMMA);
            }
          // fall through
          case 64: break;
          case 12:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_SUB);
            }
          // fall through
          case 65: break;
          case 13:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_DIV);
            }
          // fall through
          case 66: break;
          case 14:
            { return createToken(com.github.comelf.dexpr.DexprType.DECIMAL);
            }
          // fall through
          case 67: break;
          case 15:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_TERNARY_COLON);
            }
          // fall through
          case 68: break;
          case 16:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_GT);
            }
          // fall through
          case 69: break;
          case 17:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_LT);
            }
          // fall through
          case 70: break;
          case 18:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_TERNARY_QUESTION);
            }
          // fall through
          case 71: break;
          case 19:
            { return createToken(com.github.comelf.dexpr.DexprType.BRACKET_OPEN);
            }
          // fall through
          case 72: break;
          case 20:
            { return createToken(com.github.comelf.dexpr.DexprType.BRACKET_CLOSE);
            }
          // fall through
          case 73: break;
          case 21:
            { yybegin(VAR);
            }
          // fall through
          case 74: break;
          case 22:
            { /* 주석 내용 무시 */
            }
          // fall through
          case 75: break;
          case 23:
            { /* 줄바꿈 무시 */
            }
          // fall through
          case 76: break;
          case 24:
            { /* 단일 / 또는 * 문자 무시 */
            }
          // fall through
          case 77: break;
          case 25:
            { throw new DexprTokenException("Invalid character in variable (whitespace not allowed)");
            }
          // fall through
          case 78: break;
          case 26:
            { throw new DexprTokenException("Invalid character in variable: " + yytext());
            }
          // fall through
          case 79: break;
          case 27:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 80: break;
          case 28:
            { return createWrappedToken(com.github.comelf.dexpr.DexprType.STRING_PART);
            }
          // fall through
          case 81: break;
          case 29:
            { throw new DexprTokenException("Unclosed string");
            }
          // fall through
          case 82: break;
          case 30:
            { if (stringDelimiter == '"') {
            yybegin(YYINITIAL);
            return createToken(com.github.comelf.dexpr.DexprType.STRING_END);
        } else {
            return createWrappedToken(com.github.comelf.dexpr.DexprType.STRING_PART);
        }
            }
          // fall through
          case 83: break;
          case 31:
            { if (stringDelimiter == '\'') {
            yybegin(YYINITIAL);
            return createToken(com.github.comelf.dexpr.DexprType.STRING_END);
        } else {
            return createWrappedToken(com.github.comelf.dexpr.DexprType.STRING_PART);
        }
            }
          // fall through
          case 84: break;
          case 32:
            { throw new DexprTokenException("Invalid character in string variable: " + yytext());
            }
          // fall through
          case 85: break;
          case 33:
            { yybegin(STRING_STATE);
        return createToken(com.github.comelf.dexpr.DexprType.VAR_END);
            }
          // fall through
          case 86: break;
          case 34:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_NOT_EQUAL);
            }
          // fall through
          case 87: break;
          case 35:
            { return createWrappedToken(com.github.comelf.dexpr.DexprType.STRING);
            }
          // fall through
          case 88: break;
          case 36:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_AND);
            }
          // fall through
          case 89: break;
          case 37:
            { yybegin(COMMENT); comment_count = comment_count + 1;
            }
          // fall through
          case 90: break;
          case 38:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_GTE);
            }
          // fall through
          case 91: break;
          case 39:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_EQUAL);
            }
          // fall through
          case 92: break;
          case 40:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_LTE);
            }
          // fall through
          case 93: break;
          case 41:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_OR);
            }
          // fall through
          case 94: break;
          case 42:
            { comment_count = comment_count - 1;
        if(comment_count < 0)
           throw new DexprTokenException("Invalid Comment");
        if (comment_count == 0) {
            yybegin(YYINITIAL);
        }
            }
          // fall through
          case 95: break;
          case 43:
            { comment_count = comment_count + 1;
            }
          // fall through
          case 96: break;
          case 44:
            { yybegin(STRING_VAR);
        return createToken(com.github.comelf.dexpr.DexprType.VAR_START);
            }
          // fall through
          case 97: break;
          case 45:
            { return new DexprToken(com.github.comelf.dexpr.DexprType.STRING_PART, "\\");
            }
          // fall through
          case 98: break;
          case 46:
            { return new DexprToken(com.github.comelf.dexpr.DexprType.STRING_PART, "\n");
            }
          // fall through
          case 99: break;
          case 47:
            { return new DexprToken(com.github.comelf.dexpr.DexprType.STRING_PART, "\r");
            }
          // fall through
          case 100: break;
          case 48:
            { return new DexprToken(com.github.comelf.dexpr.DexprType.STRING_PART, "\t");
            }
          // fall through
          case 101: break;
          case 49:
            { return createToken(com.github.comelf.dexpr.DexprType.DOUBLE);
            }
          // fall through
          case 102: break;
          case 50:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_LIKE);
            }
          // fall through
          case 103: break;
          case 51:
            { return createToken(com.github.comelf.dexpr.DexprType.NULL);
            }
          // fall through
          case 104: break;
          case 52:
            { return createToken(com.github.comelf.dexpr.DexprType.BOOLEAN);
            }
          // fall through
          case 105: break;
          case 53:
            { return createToken(com.github.comelf.dexpr.DexprType.OPERATOR_NOT_LIKE);
            }
          // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
